FROM ghcr.io/foundry-rs/foundry

WORKDIR /app
COPY gov_foundry/ ./gov_foundry

WORKDIR /app/gov_foundry

RUN forge build
ENTRYPOINT forge script script/Setup.s.sol:Setup --rpc-url http://foundry:8545 --broadcast --code-size-limit 30000
