apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container-init-pod
  template:
    metadata:
      labels:
        app: multi-container-init-pod
    spec:
      containers:
      - name: frontend
        image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/frontend:v7
        # Main application container configuration

      - name: backend
        image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/backend:v3
        # Additional container configuration
      
      - name: foundry
        image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/foundry:v2
        # Foundry container configuration
        readinessProbe:  # Add a readiness probe to indicate when foundry is ready
          httpGet:
            path: /health  # Adjust this path based on your application
            port: 8545
          initialDelaySeconds: 5
          periodSeconds: 5

      - name: trusted
        image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/trusted:v3
        # Additional container configuration

      - name: foundry-script
        image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/foundry_script:v2
        # Init container 2 configuration
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "until nc -z foundry 8545; do sleep 1; done; /path/to/script.sh"]
              # Adjust the command to wait for the foundry container and execute the script
