apiVersion: v1
kind: Pod
metadata:
  name: multi-container-init-pod
  labels:
    app: multi-container-init-pod
spec:
  containers:
    - name: frontend
      image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/frontend:v14
      ports:
        - containerPort: 3000
    - name: backend
      image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/backend:v5
      ports:
        - containerPort: 9797
    - name: foundry
      image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/foundry:v5
      ports:
        - containerPort: 8545
    - name: trusted
      image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/trusted:v5
      ports:
        - containerPort: 9999
---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: foundry-setup-job
# spec:
#   template:
#     spec:
#       containers:
#       - name: foundry-setup-container
#         image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/foundry:v3
#         command:
#           - "sh"
#           - "-c"
#           - "sleep 10 && forge script gov_foundry/script/Setup.s.sol:Setup --rpc-url http://127.0.0.1:8545 --broadcast --code-size-limit 30000"
#         env:
#         - name: FOUNDRY_POD_IP
#           valueFrom:
#             fieldRef:
#               fieldPath: status.podIP
#       restartPolicy: Never
