apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deployment
spec:
  replicas: 1  # Number of replicas you want to run
  selector:
    matchLabels:
      app: multi-container-init-pod
  template:
    metadata:
      labels:
        app: multi-container-init-pod
    spec:
      containers:
      - name: frontend
        image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/frontend:v3
        # Main application container configuration

      - name: backend
        image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/backend:v3
        # Additional container configuration
      
      - name: foundry
        image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/foundry:v3
        # Foundry container configuration

      - name: trusted
        image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/trusted:v3
        # Additional container configuration

      - name: foundry-script
        image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/foundry_script:v3
        # Init container 2 configuration
        command: ["/bin/sh", "-c", "until nc -z foundry 8080; do sleep 1; done; /path/to/script.sh"]
        # Adjust the command to wait for the foundry container and execute the script
