apiVersion: v1
kind: Pod
metadata:
  name: multi-container-init-pod
spec:
  containers:
  - name: frontend
    image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/frontend:v2
    # Main application container configuration

  - name: backend
    image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/backend:v2
    # Additional container configuration
  
  - name: foundry
    image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/foundry:v2
    # Foundry container configuration

  - name: trusted
    image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/trusted:v2
    # Additional container configuration

  - name: foundry-script
    image: us-west2-docker.pkg.dev/governance-417015/gov-repo-final/foundry_script:v2
    # Init container 2 configuration
    command: ["/bin/sh", "-c", "until nc -z foundry 8080; do sleep 1; done; /path/to/script.sh"]
    # Adjust the command to wait for the foundry container and execute the script
